### ISSUE TITLE
Update to 0.9.0 if needed

### ISSUE THREAD

**Issue by sanex3339** [javascript-obfuscator/gulp-javascript-obfuscator#1]
Hi, please update your plugin to 0.9.0 version if needed.

Changelog here 
https://github.com/javascript-obfuscator/javascript-obfuscator/blob/master/CHANGELOG.md

**Comment by Wain-PC** [comment]
Hello! The package should be fine, as of now it will use the latest obfuscator version available.

**Comment by sanex3339** [comment]
Ok tnx
