### ISSUE TITLE
Please, update obfuscator to 0.14.3 version.

### ISSUE THREAD

**Issue by sanex3339** [javascript-obfuscator/gulp-javascript-obfuscator#10]
Please, update obfuscator to 0.14.3 version.

For each obfuscated file you should change `identifiersPrefix` option value on unique one to avoid conflicts between generated identifiers from different files.

**Comment by DRSDavidSoft** [comment]
@sanex3339 This commit shows that the latest `javascript-obfuscator` is already used:

https://github.com/javascript-obfuscator/gulp-javascript-obfuscator/commit/b8a1a29380c0d4d95aa4cbcfd18449057ecf9edf

**Comment by Wain-PC** [comment]
Yep, I've updated the obfuscator version some time ago.
