### ISSUE TITLE
Unknown provider

### ISSUE THREAD

**Issue by wwarlock** [javascript-obfuscator/gulp-javascript-obfuscator#11]
Just after install and running app with your plugin, angular started to get the next error.
```
Error: [$injector:unpr] Unknown provider: _0x159ca8Provider <- _0x159ca8 <- AppCtrl
http://errors.angularjs.org/1.6.9/$injector/unpr?p0=_0x159ca8Provider%20%3C-%20_0x159ca8%20%3C-%20AppCtrl
    at angular.js:116
    at angular.js:4887
    at Object.getService [as get] (angular.js:5047)
    at angular.js:4892
    at getService (angular.js:5047)
    at injectionArgs (angular.js:5072)
    at Object.invoke (angular.js:5098)
    at $controllerInit (angular.js:11076)
    at nodeLinkFn (angular.js:9939)
    at compositeLinkFn (angular.js:9248)
```

**Comment by raywu** [comment]
@wwarlock did you use `ngAnnotate` prior to obfuscating? Either [`gulp-ng-annotate`](https://github.com/Kagami/gulp-ng-annotate) or [`babel-plugin-angularjs-annotate`](https://github.com/schmod/babel-plugin-angularjs-annotate)

**Comment by wwarlock** [comment]
No, nothing from this in my project.
Am I must to use one of them?

**Comment by raywu** [comment]
ngAnnotate helps you manage your dependency injection before obfuscator renames everything.

**Comment by wwarlock** [comment]
Allright, I'll try and reopen this issue if that dependencies wouldn't resolve my trouble,
