### ISSUE TITLE
"gulp-javascript-obfuscator causes syntax errors"

### ISSUE THREAD

**Issue by max-edelstein** [javascript-obfuscator/gulp-javascript-obfuscator#23]
Hello,

It appears that whenever one attempts to obfuscate code with "gulp-javascript-obfuscator" certain characters are inserted in the javascript file like "}", "=", etc. These characters cause syntax errors in javascript and result in broken code. I am leaving this here in the event others run into a similar issue.

Best,

Max

**Comment by zamotkin** [comment]
@max-edelstein sorry, could you share an example of such code? I can't see your point.

**Comment by max-edelstein** [comment]
@zamotkin , I will attempt to share an example as soon as possible. My apologies for this.

**Comment by max-edelstein** [comment]
Just an update, tomorrow I plan to see if I can find the code triggering this issue.

**Comment by max-edelstein** [comment]
Issue was my fault. I was calling a task that executed gulp-uglify-es and gulp-javascript-obfuscator twice. My apologies for this.
