### ISSUE TITLE
Object spread rest not supported

### ISSUE THREAD

**Issue by kuldeeps48** [javascript-obfuscator/gulp-javascript-obfuscator#9]
Does not recognize `const message = { ip: key, ...tagStateData };`

**Comment by Wain-PC** [comment]
Hello! Seems like this syntax is not supported by the [obfuscator itself](https://github.com/javascript-obfuscator/javascript-obfuscator) (specifically, by the underlying `esprima` module). It's recommended that you transpile your code to ES5 before obfuscation.
